insert into saleinfo(s_msgtype,s_location,s_detail,s_longitude,s_latitude,s_wuye,
s_type,s_area,s_price,s_linkman,s_address,s_tel,s_email,s_publishtime,s_remark,u_id,s_high) values
(
	'出售','唐山市健康楼','唐山市健康楼1楼二单元102','100','200','普通住宅','二室一厅',
	100,50,'王先生','唐山市','13613156859','zhairuike@163.com',now(),'暂无','1','4/6'	
);

insert into saleinfo(s_msgtype,s_location,s_detail,s_longitude,s_latitude,s_wuye,
s_type,s_area,s_price,s_linkman,s_address,s_tel,s_email,s_publishtime,s_remark,u_id,s_high) values
(
	'出售','唐山市健康楼','唐山市健康楼1楼二单元102','100','200','普通住宅','二室一厅',
	100,50,'王先生','唐山市','13613156859','zhairuike@163.com',now(),'暂无','1','4/6'	
);

insert into saleinfo(s_msgtype,s_location,s_detail,s_longitude,s_latitude,s_wuye,
s_type,s_area,s_price,s_linkman,s_address,s_tel,s_email,s_publishtime,s_remark,u_id,s_high) values
(
	'出售','唐山市健康楼','唐山市健康楼1楼二单元102','100','200','普通住宅','二室一厅',
	100,50,'王先生','唐山市','13613156859','zhairuike@163.com',now(),'暂无','1','4/6'	
);

insert into saleinfo(s_msgtype,s_location,s_detail,s_longitude,s_latitude,s_wuye,
s_type,s_area,s_price,s_linkman,s_address,s_tel,s_email,s_publishtime,s_remark,u_id,s_high) values
(
	'出售','唐山市健康楼','唐山市健康楼1楼二单元102','100','200','普通住宅','二室一厅',
	100,50,'王先生','唐山市','13613156859','zhairuike@163.com',now(),'暂无','1','4/6'	
);

insert into saleinfo(s_msgtype,s_location,s_detail,s_longitude,s_latitude,s_wuye,
s_type,s_area,s_price,s_linkman,s_address,s_tel,s_email,s_publishtime,s_remark,u_id,s_high) values
(
	'求购','唐山市健康楼','唐山市健康楼1楼二单元102','100','200','普通住宅','二室一厅',
	100,50,'王先生','唐山市','13613156859','zhairuike@163.com',now(),'暂无','1','4/6'	
);

insert into saleinfo(s_msgtype,s_location,s_detail,s_longitude,s_latitude,s_wuye,
s_type,s_area,s_price,s_linkman,s_address,s_tel,s_email,s_publishtime,s_remark,u_id,s_high) values
(
	'求购','唐山市健康楼','唐山市健康楼1楼二单元102','100','200','普通住宅','二室一厅',
	100,50,'王先生','唐山市','13613156859','zhairuike@163.com',now(),'暂无','1','4/6'	
);

insert into saleinfo(s_msgtype,s_location,s_detail,s_longitude,s_latitude,s_wuye,
s_type,s_area,s_price,s_linkman,s_address,s_tel,s_email,s_publishtime,s_remark,u_id,s_high) values
(
	'求购','唐山市健康楼','唐山市健康楼1楼二单元102','100','200','普通住宅','二室一厅',
	100,50,'王先生','唐山市','13613156859','zhairuike@163.com',now(),'暂无','1','4/6'	
);

insert into saleinfo(s_msgtype,s_location,s_detail,s_longitude,s_latitude,s_wuye,
s_type,s_area,s_price,s_linkman,s_address,s_tel,s_email,s_publishtime,s_remark,u_id,s_high) values
(
	'求购','唐山市健康楼','唐山市健康楼1楼二单元102','100','200','普通住宅','二室一厅',
	100,50,'王先生','唐山市','13613156859','zhairuike@163.com',now(),'暂无','1','4/6'	
);

insert into saleinfo(s_msgtype,s_location,s_detail,s_longitude,s_latitude,s_wuye,
s_type,s_area,s_price,s_linkman,s_address,s_tel,s_email,s_publishtime,s_remark,u_id,s_high) values
(
	'求购','唐山市健康楼','唐山市健康楼1楼二单元102','100','200','普通住宅','二室一厅',
	100,50,'王先生','唐山市','13613156859','zhairuike@163.com',now(),'暂无','1','4/6'	
);

insert into rentinfo(r_msgtype,r_location,r_detail,r_longitude,r_latitude,r_wuye,r_type,r_area,
r_lease,r_price,r_linkman,r_address,r_tel,r_email,r_publishtime,r_remark,u_id,r_high) values
(
	'出租','唐山市新华楼','唐山市新华楼19楼一单元201',100,200,'普通住宅','一室一厅',30,6,
	200,'李先生','唐山市新华楼','13503376659','zhaibing@sina.com',now(),'暂无',1,'2/6'
);
insert into rentinfo(r_msgtype,r_location,r_detail,r_longitude,r_latitude,r_wuye,r_type,r_area,
r_lease,r_price,r_linkman,r_address,r_tel,r_email,r_publishtime,r_remark,u_id,r_high) values
(
	'出租','唐山市新华楼','唐山市新华楼19楼一单元201',100,200,'普通住宅','一室一厅',30,6,
	200,'李先生','唐山市新华楼','13503376659','zhaibing@sina.com',now(),'暂无',1,'2/6'
);
insert into rentinfo(r_msgtype,r_location,r_detail,r_longitude,r_latitude,r_wuye,r_type,r_area,
r_lease,r_price,r_linkman,r_address,r_tel,r_email,r_publishtime,r_remark,u_id,r_high) values
(
	'出租','唐山市新华楼','唐山市新华楼19楼一单元201',100,200,'普通住宅','一室一厅',30,6,
	200,'李先生','唐山市新华楼','13503376659','zhaibing@sina.com',now(),'暂无',1,'2/6'
);
insert into rentinfo(r_msgtype,r_location,r_detail,r_longitude,r_latitude,r_wuye,r_type,r_area,
r_lease,r_price,r_linkman,r_address,r_tel,r_email,r_publishtime,r_remark,u_id,r_high) values
(
	'出租','唐山市新华楼','唐山市新华楼19楼一单元201',100,200,'普通住宅','一室一厅',30,6,
	200,'李先生','唐山市新华楼','13503376659','zhaibing@sina.com',now(),'暂无',1,'2/6'
);
insert into rentinfo(r_msgtype,r_location,r_detail,r_longitude,r_latitude,r_wuye,r_type,r_area,
r_lease,r_price,r_linkman,r_address,r_tel,r_email,r_publishtime,r_remark,u_id,r_high) values
(
	'求租','唐山市新华楼','唐山市新华楼19楼一单元201',100,200,'普通住宅','一室一厅',30,6,
	200,'李先生','唐山市新华楼','13503376659','zhaibing@sina.com',now(),'暂无',1,'2/6'
);
insert into rentinfo(r_msgtype,r_location,r_detail,r_longitude,r_latitude,r_wuye,r_type,r_area,
r_lease,r_price,r_linkman,r_address,r_tel,r_email,r_publishtime,r_remark,u_id,r_high) values
(
	'求租','唐山市新华楼','唐山市新华楼19楼一单元201',100,200,'普通住宅','一室一厅',30,6,
	200,'李先生','唐山市新华楼','13503376659','zhaibing@sina.com',now(),'暂无',1,'2/6'
);
insert into rentinfo(r_msgtype,r_location,r_detail,r_longitude,r_latitude,r_wuye,r_type,r_area,
r_lease,r_price,r_linkman,r_address,r_tel,r_email,r_publishtime,r_remark,u_id,r_high) values
(
	'求租','唐山市新华楼','唐山市新华楼19楼一单元201',100,200,'普通住宅','一室一厅',30,6,
	200,'李先生','唐山市新华楼','13503376659','zhaibing@sina.com',now(),'暂无',1,'2/6'
);
insert into rentinfo(r_msgtype,r_location,r_detail,r_longitude,r_latitude,r_wuye,r_type,r_area,
r_lease,r_price,r_linkman,r_address,r_tel,r_email,r_publishtime,r_remark,u_id,r_high) values
(
	'求租','唐山市新华楼','唐山市新华楼19楼一单元201',100,200,'普通住宅','一室一厅',30,6,
	200,'李先生','唐山市新华楼','13503376659','zhaibing@sina.com',now(),'暂无',1,'2/6'
);